### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by huftre** [yichungwang/GifSearcher#1]
The app crashes in the search results controller during scrolling. Xcode crashes on the error you see in the image.
![18358887_10211472804688298_4983548329062363306_o](https://cloud.githubusercontent.com/assets/15199043/25944580/18678c2c-3644-11e7-9a70-9f2f00482594.jpg)

**Comment by yichungwang** [comment]
Hi, I also included the pods. Try and see if the error still exists. Thanks.

**Comment by huftre** [comment]
When I try to search gif with a word, for example, "woman" app freezes, it freezes and the console does not return anything. By pausing the debug here is what goes out
Can I have a personal email for you to write?
![18451952_10211477461124706_985235399_o](https://cloud.githubusercontent.com/assets/15199043/25992709/b68d1d18-3707-11e7-9021-71452829aed8.png)

**Comment by yichungwang** [comment]
Hi, I figured out why. 73b87cd0f67e627017f7dc5c65816f0549fe62b8
Take a look and see if error still exists and feel free to email me at: ccw373@nyu.edu

**Comment by yichungwang** [comment]
going to close this for now, reopen if you encounter any more errors
